### ISSUE TITLE
MMM. Google TTS sent TTS_Say_Error

### ISSUE THREAD

**Issue by CyberRagz** [eouia/MMM-GoogleTTS#6]
I have installed the module and configured the Google tts API. On  starting magic mirror and sending /tts  message on telegram, i am getting notification as MMM-Google TTS sent "TTS_Say_ error".  I have checked my Google TTS API account and there is no error or i am unable to understand if at all there is some configuratin issue. Also, the service hasn't been used even once so obviously there is no issue of quota limit.
How to debug and resolve?

**Comment by eouia** [comment]
Do you have a log about it?

To test the module working;
1) Remove all other modules unrelated; even TelegramBot also. Let's keep the mirror simple as possible.

2) in the config, you need to watch out these properties;

```js
welcome: "This module is working",
```
If module works; this message would be spoken on startup.

```js
 playCommand: "aplay %OUTPUTFILE%",
 ```
When you use other OS/Device you may adjust this option for your environment;
- test like this.
```sh
aplay whatever_you_have.wav 
```
If that sounds as expected, everything is fine. But if you get the error or no sound, you need to find a proper command for your environment. Sometimes, your RPI might need some additional options like this; 
```sh
aplay -D plughw:1,0 whatever_you_have.wav
```
In that case, you should adjust your config like this;
```js
playCommand: "aplay -D plughw:1,0 %OUTPUTFILE%
```
Or if you are using other Device like MacMini; you might need `afplay` or `mpg321` instead of `aplay`. Read the README document (https://github.com/MMRIZE/MMM-GoogleTTS/blob/master/README.md)
